backend:
  name: git-gateway
  branch: main

media_folder: "public/assets"
public_folder: "/assets"

collections:

  # 1) File-based collection para FAQs
  - label: "Preguntas Frecuentes"
    name: "faqs"
    files:
      - label: "Listado de FAQs"
        name: "faqs_json"
        file: "public/content/faqs.json"
        fields:
          - label: "items"
            name: "items"
            widget: list
            fields:
              - label: "Pregunta"
                name: "pregunta"
                widget: string
              - label: "Respuesta"
                name: "respuesta"
                widget: text

  # 2) Folder-based collection para Galería
  - label: "Galería"
    name: "gallery"
    folder: "public/content/gallery"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - label: "Título"
        name: "titulo"
        widget: string

      - label: "Categoría"
        name: "categoria"
        widget: select
        options:
          - "muebles"
          - "mesas"
          - "escaleras"
          - "portones"

      - label: "Imagen"
        name: "imagen"
        widget: image

      - label: "Thumbnail"
        name: "thumb"
        widget: image
