backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "gallery"
    label: "Galería"
    folder: "content"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Categoría", name: "categoria", widget: "select", options: ["muebles","mesas","escaleras","portones"] }
      - { label: "Título",      name: "titulo",     widget: "string" }
      - { label: "Imagen",      name: "imagen",     widget: "image" }
      - { label: "Thumbnail",   name: "thumb",      widget: "image", required: false }

  - name: "faqs"
    label: "FAQs"
    folder: "content"
    create: true
    slug: "{{slug}}"
    extension: "json"
    fields:
      - { label: "Pregunta", name: "pregunta", widget: "string" }
      - { label: "Respuesta", name: "respuesta", widget: "text" }
