backend:
  name: github
  repo: ludmilasolutions/soldarte

media_folder: "public/assets"
public_folder: "/assets"

collections:
  - name: "gallery"
    label: "Galería"
    files:
      - label: "Galería de Trabajos"
        name: "gallery"
        file: "public/content/gallery.json"
        fields:
          # Aquí declaramos el list de items
          - 
            label: "Entradas"
            name: "items"
            widget: "list"
            summary: "{{fields.titulo}} ({{fields.categoria}})"
            fields:
              - { label: "Título",      name: "titulo", widget: "string" }
              - { label: "Imagen",      name: "imagen", widget: "image" }
              - { label: "Miniatura",   name: "thumb",  widget: "image", required: false }
              - label: "Categoría"
                name: "categoria"
                widget: "select"
                options:
                  - { label: "Muebles",     value: "muebles" }
                  - { label: "Mesas",       value: "mesas" }
                  - { label: "Escaleras",   value: "escaleras" }
                  - { label: "Portones",    value: "portones" }

  - name: "faqs"
    label: "FAQs"
    files:
      - label: "Preguntas Frecuentes"
        name: "faqs"
        file: "public/content/faqs.json"
        fields:
          - 
            label: "Entradas"
            name: "items"
            widget: "list"
            summary: "{{fields.pregunta}}"
            fields:
              - { label: "Pregunta",   name: "pregunta", widget: "string" }
              - { label: "Respuesta",  name: "respuesta", widget: "text" }
