collections:

  # ——— Galería en un único fichero ———
  - name: "gallery"
    label: "Galería"
    files:
      - file: "public/content/gallery.json"
        name: "gallery"
        label: "Galería completa"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - label: "Título"
                name: "titulo"
                widget: "string"
              - label: "Categoría"
                name: "categoria"
                widget: "select"
                options:
                  - "muebles"
                  - "mesas"
                  - "escaleras"
                  - "portones"
              - label: "Imagen"
                name: "imagen"
                widget: "image"
              - label: "Thumb"
                name: "thumb"
                widget: "image"
                required: false

  # ——— FAQs en un único fichero ———
  - name: "faqs"
    label: "Preguntas Frecuentes"
    files:
      - file: "public/content/faqs.json"
        name: "faqs"
        label: "FAQs completas"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            fields:
              - label: "Pregunta"
                name: "pregunta"
                widget: "string"
              - label: "Respuesta"
                name: "respuesta"
                widget: "text"
