# ─── Backend ────────────────────────────────────────────────────────────────
backend:
  name: git-gateway     # usa Netlify Identity + Git Gateway
  branch: main          # tu rama principal

# ─── Media (imágenes) ───────────────────────────────────────────────────────
media_folder: "assets/uploads"   # ruta en tu repo donde se guardan las subidas
public_folder: "/assets/uploads" # ruta pública desde el navegador

media_library:                   # plugin de Uploadcare con demo key
  name: uploadcare
  config:
    publicKey: "demopublickey"

# ─── Colecciones ────────────────────────────────────────────────────────────
collections:

  # ——— Galería: un solo JSON con todos los items ———
  - name: "gallery"
    label: "Galería"
    files:
      - file: "public/content/gallery.json"
        name: "gallery"
        label: "Galería completa"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.titulo}} ({{fields.categoria}})"
            fields:
              - label: "Título"
                name: "titulo"
                widget: "string"
              - label: "Categoría"
                name: "categoria"
                widget: "select"
                options:
                  - "muebles"
                  - "mesas"
                  - "escaleras"
                  - "portones"
              - label: "Imagen"
                name: "imagen"
                widget: "image"
              - label: "Thumb (opcional)"
                name: "thumb"
                widget: "image"
                required: false

  # ——— FAQs: un solo JSON con todas las preguntas ———
  - name: "faqs"
    label: "Preguntas frecuentes"
    files:
      - file: "public/content/faqs.json"
        name: "faqs"
        label: "FAQs completas"
        fields:
          - label: "Items"
            name: "items"
            widget: "list"
            summary: "{{fields.pregunta}}"
            fields:
              - label: "Pregunta"
                name: "pregunta"
                widget: "string"
              - label: "Respuesta"
                name: "respuesta"
                widget: "text"
